name: Build LaTeX document
on: [push, pull_request]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@v3
      with:
        working_directory: src/dacs-sw/control-station-installation/
        root_file: main.tex
        work_in_root_file_dir: true

    - name: Upload PDF file
      uses: actions/upload-artifact@v4
      with:
        name: PDF
        path: main.pdf
