name: Build LaTeX document
on: [push, pull_request]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Compile all LaTeX documents
      run: python3 scripts/compile-all-latex.py

    - name: Rename files and move to single release folder
      run: |
        mkdir --parents release
        python3 scripts/move-files.py

    - name: Upload PDF files
      uses: actions/upload-artifact@v4
      with:
        name: artifacts
        path: release/*
