name: Build LaTeX document
on: [push, pull_request]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Compile all LaTeX documents
      run: |
        projects=("control-station-installation" "template" "database-ingestion")
        for project in "${projects[@]}"; do
          working_directory="src/dacs-sw/$project"
          root_file="main.tex"
          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace/$working_directory texlive/texlive:latest latexmk -pdf -interaction=nonstopmode $root_file
        done

    - name: Rename files and move to single release folder
      run: |
        mkdir --parents release
        python3 scripts/move-files.py

    - name: Upload PDF files
      uses: actions/upload-artifact@v4
      with:
        name: artifacts
        path: release/*
