name: "Make release"
on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write # Needed to write to GitHub draft release

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@v3
      with:
        working_directory: src/dacs-sw/control-station-installation/
        root_file: main.tex
        work_in_root_file_dir: true

    - name: Make release with PDFs
      uses: softprops/action-gh-release@v2
      with:
        files: |
          src/dacs-sw/control-station-installation/main.pdf
