name: tagpr
on:
  push:
    branches: ["main"]

jobs:
  tagpr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - id: tagpr
      uses: Songmu/tagpr@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Remove waterkmark
      if: ${{ steps.tagpr.outputs.tag != '' }}
      # Set the variable controlling the watermark addition to `false`
      run: |
        sed -i 's/\\setboolean{isDraft}{true}/\\setboolean{isDraft}{false}/' src/dacs-sw/control-station-installation/main.tex

    - name: Compile LaTeX document
      if: ${{ steps.tagpr.outputs.tag != '' }}
      uses: xu-cheng/latex-action@v3
      with:
        working_directory: src/dacs-sw/control-station-installation/
        root_file: main.tex
        work_in_root_file_dir: true

    - name: Make release with PDFs
      if: ${{ steps.tagpr.outputs.tag != '' }}
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.tagpr.outputs.tag }}
        files: |
          src/dacs-sw/control-station-installation/main.pdf
