name: tagpr
on:
  push:
    branches: ["main"]

jobs:
  tagpr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - id: tagpr
      uses: Songmu/tagpr@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Remove watermark
      if: ${{ steps.tagpr.outputs.tag != '' }}
      # Set the variable controlling the watermark addition to `false`
      run: |
        sed -i 's/\\setboolean{isDraft}{true}/\\setboolean{isDraft}{false}/' src/common/lib/header.tex

    - name: Compile all LaTeX documents
      if: ${{ steps.tagpr.outputs.tag != '' }}
      run: |
        projects=("control-station-installation" "template" "database-ingestion")
        for project in "${projects[@]}"; do
          working_directory="src/dacs-sw/$project"
          root_file="main.tex"
          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace/$working_directory texlive/texlive:latest latexmk -pdf -interaction=nonstopmode $root_file
        done

    - name: Rename files and move to single release folder
      if: ${{ steps.tagpr.outputs.tag != '' }}
      run: |
        mkdir --parents release
        mv src/dacs-sw/control-station-installation/main.pdf release/dacs-sw-control-station-installation.pdf
        mv src/dacs-sw/template/main.pdf release/dacs-sw-template.pdf
        mv src/dacs-sw/database-ingestion/main.pdf release/dacs-sw-database-ingestion.pdf

    - name: Make release with PDFs
      if: ${{ steps.tagpr.outputs.tag != '' }}
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.tagpr.outputs.tag }}
        files: |
          release/*
