name: tagpr
on:
  push:
    branches: ["main"]

jobs:
  tagpr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - id: tagpr
      uses: Songmu/tagpr@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Remove watermark
      if: ${{ steps.tagpr.outputs.tag != '' }}
      # Set the variable controlling the watermark addition to `false`
      run: |
        sed -i 's/\\setboolean{isDraft}{true}/\\setboolean{isDraft}{false}/' src/common/lib/header.tex

    - name: Compile all LaTeX documents
      if: ${{ steps.tagpr.outputs.tag != '' }}
      run: python3 scripts/compile-all-latex.py

    - name: Rename files and move to single release folder
      if: ${{ steps.tagpr.outputs.tag != '' }}
      run: |
        mkdir --parents release
        python3 scripts/move-files.py

    - name: Make release with PDFs
      if: ${{ steps.tagpr.outputs.tag != '' }}
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.tagpr.outputs.tag }}
        files: |
          release/*
